apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 8
  template:
    metadata:
      labels:
        app: my-application
        role: api
    spec:
      containers:
        - name: api
          image: pottava/proxy:1.1
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 8080
          env:
          - name: PROXY_URL
            value: http://localhost/
          - name: APP_PORT
            value: "8080"
          - name: ACCESS_LOG
            value: "true"
          - name: HEALTHCHECK_PATH
            value: /health
          resources:
            requests:
              cpu: 100m
              memory: 20Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
        - name: web
          image: dockercloud/hello-world
          ports:
          - containerPort: 80
            protocol: TCP
          env:
          - name: NAME
            value: k8s-federated-clusters
          resources:
            requests:
              cpu: 10m
              memory: 30Mi
