apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 8
  template:
    metadata:
      labels:
        app: my-application
        role: api
    spec:
      containers:
        - name: api
          image: pottava/http-re:1.1
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 9000
          env:
          - name: API_PORT
            value: "9000"
          - name: APP_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: APP_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: APP_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: APP_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:1
          args: [
            "-p", "8080",
            "-a", "127.0.0.1:9000",
            "-s", "www.pottava.com",
            "-v", "2017-10-08r0",
            "-z", "health",
          ]
          ports:
            - protocol: TCP
              containerPort: 8080
          resources:
            requests:
              cpu: 70m
              memory: 30Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
