apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 8
  template:
    metadata:
      labels:
        app: my-application
        role: api
    spec:
      containers:
        - name: api
          image: pottava/http-re:1.0
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 8080
          env:
          - name: APP_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: APP_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: APP_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: APP_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
