apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: my-application
    role: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30000
